export default{
    APP_OPERATION:"APP_OPERATION",
    APP_TOURSHOW:"APP_TOURSHOW",
    APP_MEMBERSHIP:"APP_MEMBERSHIP",
    APP_HOTVENUE:"APP_HOTVRNUE",
    GET_PIC:"GET_PIC",
    GET_HOTSHOW:"GET_HOTSHOW",
    GET_LIST : "GET_LIST",
    GET_LODINGLIST:"GET_LODINGLIST"
}
